appName: API-PROXY
port: 8080
defaultTimeout: 10000
maxCacheMemory: 50
dashboard: true
rootPath: /

storage:
  redis:
    enabled: false
    host: localhost
    port: 6379
    database: 1
  statsd:
    enabled: false
    host: localhost
    port: 8011
    prefix: my.prefix
  inMemory:
    enabled: true

proxies:
  - path: /httpbin
    service: httpbinApi
    middleware: 'basicAuth:roleA'
    ttl: -1
  - path: /example
    service: exampleApi
    middleware: ''
    ttl: -1
  - path: /google
    service: googleApi
    middleware: ''
    ttl: -1
  - path: /products
    service: productApi
    middleware: 'basicAuth:roleA'
    ttl: -1
  - path: /task
    service: tasksApi
    middleware: 'basicAuth:roleB'
    ttl: 1000

services:
  - name: tasksApi
    url: http://localhost:5173/template/1on1-meeting-agenda/tasks.json
    methods: ['GET', 'POST', 'PUT']
    role: userA
  - name: productApi
    url: https://dummyjson.com/products
    methods: ['GET']
    role: userA
  - name: googleApi
    url: http://www.google.com
    methods: ['GET', 'POST', 'PUT']
    role: userB
  - name: exampleApi
    url: http://example.com
    methods: ['GET', 'POST', 'PUT']
  - name: httpbinApi
    url: http://httpbin.org
    methods: ['GET', 'POST', 'PUT']

realmPath: src/main/resources/realm.properties
realmName: MyName

users:
  - username: userA
    password: passwordA
    role: roleA
  - username: userB
    password: passwordB
    role: roleB