appName: ${JET_APP_NAME:API-PROXY}
port: ${JET_PORT:8080}
defaultTimeout: ${JET_DEFAULT_TIMEOUT:10000}
dashboard: ${JET_DASHBOARD:true}
rootPath: ${JET_DASHBOARD:/}
debugMode: ${JET_DEBUG_MODE:true}
corsFilter:
  accessControlAllowMethods:
    - "*"
  accessControlAllowHeaders:
    - "*"
  accessControlAllowOriginList:
    - "*"

storage:
  redis:
    enabled: true
    host: localhost
    port: 6379
    database: 1
    maxTotal: 128
    maxIdle: 64
    minIdle: 16
  statsd:
    enabled: false
    host: localhost
    port: 8011
    prefix: my.prefix
  inMemory:
    enabled: true
    maxMemory: 50 # MB
    size: 10000

proxies:
  - path: /httpbin
    service: httpbinApi
    ttl: -1
  - path: /example
    service: exampleApi
    ttl: -1
  - path: /google
    service: googleApi
    ttl: -1
  - path: /user
    service: userApi
    middleware:
      circuitBreaker:
        enabled: true
        failureThreshold: 30 # 50% failure rate threshold
        slowCallThreshold: 50 # 50% slow call rate threshold
        slowCallDuration: 500 # 0.5 seconds threshold for slow calls
        openStateDuration: 5 # 5-second wait in open state
        waitDurationInOpenState: 10000  # 10-second wait in open state
        permittedNumberOfCallsInHalfOpenState: 2 # 3 calls in half-open state
        minimumNumberOfCalls: 4 # Minimum of 4 calls before evaluating
      header:
        requestHeaders: "Remove(x-header-*);Remove(Authorization);Append(X-Custom-Header,-jetty)"
        responseHeaders: "Add(X-Powered-By,jetty-server)"
    ttl: -1
  - path: /products
    service: productApi
    middleware:
      basicAuth: 'basicAuth:roleA'
      forwardAuth:
        path: /verify
        service: authApi
        authRequestHeaders: "Forward(X-Custom-*);Forward(Authorization)"
      rule: "(Header('Content-Type', 'application/json') && HeaderPrefix('User-Agent', 'Mozilla')) || HeaderRegex('X-Custom-Header', '^[a-zA-Z0-9]{10}$')"
      circuitBreaker:
        enabled: true
        failureThreshold: 50 # 50% failure rate threshold
        slowCallThreshold: 50 # 50% slow call rate threshold
        slowCallDuration: 2000 # 2 seconds threshold for slow calls
        openStateDuration: 10 # 10-second wait in open state
        waitDurationInOpenState: 10000  # 10-second wait in open state
        permittedNumberOfCallsInHalfOpenState: 3 # 3 calls in half-open state
        minimumNumberOfCalls: 5 # Minimum of 5 calls before evaluating
    ttl: -1
  - path: /task
    service: tasksApi
    middleware:
      header:
        requestHeaders: "Forward(X-Custom-*);Forward(Authorization)"
        responseHeaders: "Append(x-ganteng,andy)"
      basicAuth: 'basicAuth:roleB'
      forwardAuth:
        path: /verify
        service: authApi
        authRequestHeaders: "Forward(X-Custom-*);Forward(Authorization)"
      rule: "(Header('Content-Type', 'application/json') && HeaderPrefix('User-Agent', 'Mozilla')) || HeaderRegex('X-Custom-Header', '^[a-zA-Z0-9]{10}$')"
    ttl: 10000

services:
  - name: tasksApi
    url: http://localhost:5173/template/1on1-meeting-agenda/tasks.json
    methods: ['GET', 'POST', 'PUT']
    healthcheck: /ping
  - name: productApi
    url: https://dummyjson.com/products
    methods: ['GET']
    role: userA
    healthcheck: /ping
  - name: googleApi
    url: http://www.google.com
    methods: ['GET', 'POST', 'PUT']
  - name: exampleApi
    url: http://example.com
    methods: ['GET', 'POST', 'PUT']
  - name: httpbinApi
    url: http://httpbin.org
    methods: ['GET', 'POST', 'PUT']
  - name: authApi
    url: http://localhost:30001
    methods: ['POST']
  - name: userApi
    url: http://localhost:30001
    methods: ['GET']

users:
  - username: admin
    password: admin
    role: administrator
  - username: userA
    password: passwordA
    role: roleA
  - username: userB
    password: passwordB
    role: roleB




