appName: ${JET_APP_NAME:API-PROXY}
port: ${JET_PORT:8080}
defaultTimeout: ${JET_DEFAULT_TIMEOUT:10000}
dashboard: ${JET_DASHBOARD:true}
rootPath: ${JET_DASHBOARD:/}
#debugLog: ${JET_DEBUG_LOG_MODE:true}
accessLog: ${JET_DEBUG_MODE:true}

logging:
  root:
    level: INFO
  appenders:
    - name: STDOUT
      className: "ch.qos.logback.core.ConsoleAppender"
      encoder:
        pattern: "%d{yyyy-MM-dd HH:mm:ss} %-1level %logger{36} - %msg%n"
#  loggers:
#    - name: "io.jetproxy"
#      level: INFO
#    - name: "org.eclipse.jetty"
#      level: INFO


corsFilter:
  accessControlAllowMethods:
    - "*"
  accessControlAllowHeaders:
    - "*"
  accessControlAllowOriginList:
    - "*"

storage:
  redis:
    enabled: false
    host: localhost
    port: 6379
    database: 1
    maxTotal: 128
    maxIdle: 64
    minIdle: 16

  inMemory:
    enabled: true
    maxMemory: 50 # MB
    size: 10000

proxies:
  - path: /v2/grpc
    service: userGrpcApi
    ttl: 10000
  - path: /user
    service: userApi
    matches:
      - rule: "Header('Content-Type', 'application/json')"
        service: userApi
      - rule: "Header('x-header-hello', 'x-header-hello')"
        service: userApi
    middleware:
      mirroring:
        enabled: true
        mirrorService: userV2Api
        mirrorPercentage: 100
    ttl: 1000
services:
  - name: userApi
    url: http://localhost:30001
    methods: ['GET', 'POST']
  - name: userV2Api
    url: http://localhost:30001/v2
    methods: [ 'GET', 'POST']

grpcServices:
  - name: userGrpcApi
    host: localhost                   # Host for gRPC server
    port: 50051                       # Port for gRPC server


#  - name: userV2Api
#    host: localhost                   # Host for gRPC server
#    port: 30001                       # Port for gRPC server
#    basePath: /v2                    # Version base path for this service

users:
  - username: admin
    password: admin
    role: administrator


