port: 8080
defaultTimeout: 10000
maxCacheMemory: 50 # use MB
dashboard: true
metrics:
  redis:
    enabled: true
    host: localhost
    port: 6379
    database: 1
  statsd:
    enabled: true
    host: localhost
    port: 8011
    prefix: my.prefix
  inMemory:
    enabled: true
proxies:
  - path: /httpbin
    service: httpbinApi
    middleware: ''
    ttl: -1
  - path: /example
    service: exampleApi
    middleware: ''
    ttl: -1
  - path: /google
    service: googleApi
    middleware: ''
    ttl: -1
  - path: /products
    service: productApi
    middleware: ''
    ttl: -1
  - path: /task
    service: tasksApi
    middleware: ''
    ttl: 100
services:
  - name: tasksApi
    url: http://localhost:5173/template/1on1-meeting-agenda/tasks.json
    methods: ['GET', 'POST', 'PUT']
  - name: productApi
    url: https://dummyjson.com/products
    methods: ['GET']
  - name: googleApi
    url: http://www.google.com
    methods: ['GET', 'POST', 'PUT']
  - name: exampleApi
    url: http://example.com
    methods: ['GET', 'POST', 'PUT']
  - name: httpbinApi
    url: http://httpbin.org
    methods: ['GET', 'POST', 'PUT']

