version: '3.7'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Collector endpoint
      - "14250:14250"  # GRPC endpoint
      - "6831:6831/udp" # Agent endpoint for UDP traffic
      - "6832:6832/udp" # Agent endpoint for UDP traffic
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411  # Optional for Zipkin endpoint compatibility

  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: opentelemetry-collector
    ports:
      - "4317:4317"  # OTLP GRPC
      - "55681:55681"  # OTLP HTTP
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
