name: CI Pipeline

on:
  pull_request:
    branches:
      - main   # Specify the branch you're merging into (e.g., main or master)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use Adoptium distribution
          java-version: '21'       # Specify JDK 21 here

      # Step 3: Cache Gradle dependencies (optional, but speeds up the build)
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Build and run tests
      - name: Build and Run Unit Tests
        run: ./gradlew test --no-daemon

      # Optional: Upload test results or logs
      - name: Upload test results
        if: failure()  # Only upload if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/test-results/test
