name: CI and Release Pipeline

on:
  pull_request:
    branches:
      - main   # Run CI on pull requests to main
  push:
    tags:
      - 'v*'   # Trigger the release workflow on version tags (e.g., v1.0.0)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 22
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use Adoptium distribution
          java-version: '22'

      # Step 3: Cache Gradle dependencies (optional)
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Build and run tests
      - name: Build and Run Unit Tests
        run: ./gradlew test --no-daemon

  release:
    runs-on: ubuntu-latest
    needs: test   # Ensure tests pass before creating a release
    if: github.ref_type == 'tag'  # Run only when a tag is pushed

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 22
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      # Step 3: Build the JAR file
      - name: Build JAR
        run: ./gradlew clean build --no-daemon

      # Step 4: Upload JAR to GitHub Release
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar  # Adjust this path to match your JAR output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
